### ISSUE TITLE
switch R versions

### ISSUE THREAD

**Issue by slowkow** [r-hub/node-install-rstats#15]
Thanks for the convenient package!

An email from CRAN notified me that my package ggrepel has errors on `devel`.

So, I went ahead and ran `install-rstats devel`.

After compiling some packages for a few hours, I was finally able to reproduce the errors! Hooray.

Now I want to get back to my old R (4.0). How do I do it quickly without having to reinstall and recompile everything?

**Comment by slowkow** [comment]
It seems like `install-rstats release` has put me back on R 4.0.3. Hooray!

OK, maybe this was easier than I thought. Thanks again!

**Comment by gaborcsardi** [comment]
Yeah, it could have a script for that. You could use https://rud.is/rswitch/ which can change the active version.

Or you can do it manually from a shell:
```
sudo ln -fsn /Library/Frameworks/R.framework/Versions/4.0 /Library/Frameworks/R.framework/Versions/Current
```
